spring:
  application:
    name: platform-eureka

---
server:
  port: 7001
spring:
  profiles: peer1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:7001
  client:
    registerWithEureka: true                                                         # 表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    fetchRegistry: true                                                              #  表示是否从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:7002/eureka/
  server:
    enable-self-preservation: false

---
server:
  port: 7002
spring:
  profiles: peer2
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:7002
  client:
    registerWithEureka: true                                                         # 表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    fetchRegistry: true                                                              #  表示是否从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  server:
    enable-self-preservation: false
